# Generated by Django 5.1.1 on 2024-10-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ads_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'ordering': ['-created_at']},
        ),
    ]
