# Generated by Django 5.1.1 on 2024-10-09 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ads_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='ads',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='ads_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
