# Generated by Django 5.1.1 on 2024-10-09 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ads_total_likes_ads_users_like'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='ad',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='ads.ads'),
            preserve_default=False,
        ),
    ]
